// don't modify this file by hand, it is automatically generated by build.rs, for nametag.

#[macro_export] macro_rules! name { ($i:ident) => {crate::names::$i} }

nametag::setup_names! {
    Position,
    Roughness,
    MainDepth,
    Albedo,
    Normal,
    Metallic,
    
}